### PR TITLE
Schedule callbacks on a connection in a go routine to preserve order

### PR DESCRIPTION
**Pull request by kozlovic**
@derekcollison This seems overly complex to me, and not really go-like. Would appreciate pointers on how to do this differently.

### CODE REVIEW

**Comment by derekcollison** [comment]
I agree, this is pretty complex. I think we can come up with something simpler and have one Go routine per Connection. It selects over ConnHandler chan (connect, reconnect, disconnect) and an ErrHandler chan and a quit condition. Let me give this a pass and see what I can come up with.

**Comment by kozlovic** [comment]
Appreciate it. I did not want to use a channel (other than to notify that the list should be processed) because of the size of the channel. If it is unbuffered, we would potentially block. If buffered, what size to use (reference to removing channel for async msgs come to mind)?

**Comment by derekcollison** [comment]
The connHandler is not very many events, so 4 or 8 buffered size. The
ErrHandler may be more, but if it comes from the server we will be
disconnected, and if it is from client side slowConsumer we gate it.

**Comment by kozlovic** [comment]
I thought about it, but technically, the same connection could go through a list of disconnect - reconnect -disconnect - reconnect - disconnect - etc... possibly rapidly.

**Comment by derekcollison** [comment]
Not sure how rapid or how common, but I understand what you are saying.

**Comment by kozlovic** [comment]
If we have a select for conn handler and one for async err handler, then the total order would not be respected. If we are ok with that, I can have another go at trying to implement this.
That being said, for async, we still need to not only push a function, but there are the sub and err to pass around that may be different each time.

**Comment by derekcollison** [comment]
You can close over the arguments.

**Comment by kozlovic** [comment]
@derekcollison Not sure if this is closer to what you had in mind.

The issue I have with that approach is that async cbs may be out-of-order compared to connection callbacks (due to the use of different channels). Also, the use of a buffered channel scares me, especially that for async err, we send to the channel from readLoop thread, and if we block there (channel full) while the user tries to close the connection from async err callback, we'll deadlock.

The initial approach was ugly, but it did not have any of the above issues.

**Comment by kozlovic** [comment]
Closing this PR since covered in other one.

**Pull request closed without merging**
