### PR TITLE
Update to use ErrMaxMessages constant

### PR DESCRIPTION
**Pull request by mcqueary**

### CODE REVIEW

**Comment by mcqueary** [comment]
The test that failed (TestHotSpotReconnect) has nothing to do with `ErrMaxMessages` in `nats.go`. Must be an unrelated timing issue.

**Comment by derekcollison** [comment]
I may hold off a wee bit to merge my current branch first. Just fyi.

**Comment by mcqueary** [comment]
No worries, I just forgot to change that when I updated the constants a couple weeks back.

**Comment by derekcollison** [comment]
Did this in other PR.

**Pull request closed without merging**
