### PR TITLE
Added a queueing subscriber to the example programs

### PR DESCRIPTION
**Pull request by jduhamel**
Created a nats-qsub.go example. Main difference from nats-sub.go is that I called QueueSubscribe and printed out the queue name as well as the pid of the executable in the printMsg function for demonstration purposes otherwise it's identical to nats-sub.go

Changes:
*Second argument is queue name. 
*Subscribe call is to QueueSubscribe
*printMsg prints 2 additional pieces of information. queue name and process id.

### CODE REVIEW

**Comment by derekcollison** [comment]
Why not just add a queue group flag to nats-sub?

**Comment by jduhamel** [comment]
Can do very easily. I was trying to keep the examples as clean as possible. Obviously there are only 3 changes in the code so I can wrap them with a if queueExample construct. 

Question is more to you about do you want to provide a minimal number of example or provide a set of examples that cover the major modalities. pub/sub queuing and request reply. 

-Joe

**Comment by derekcollison** [comment]
You might have a point.

**Comment by jduhamel** [comment]
Following up on this you would only need (or I can send the ones I have) a simple nats-req.go and a nats-rply.go to complete the set. My major driver for doing the nats-qsub was the documentation on the doc site was wrong and just wanted to put the raw materials out there.

**Comment by derekcollison** [comment]
sure send them along too, or add them to this PR.

**Comment by jduhamel** [comment]
Let me know what you want to do. -Joe

**Comment by mcqueary** [comment]
LGTM. We'll want to include equivalent examples in the other clients.

/cc @nats-io/dev

**Pull request merged**
