### PR TITLE
Fix error in next message after encode/decode fail in previous

### PR DESCRIPTION
**Pull request by AnatoliiPrylutskyi**
This issue was discussed in https://github.com/nats-io/nats/issues/78

I create test cases to reproduce errors
You can checkout this commit with failed tests https://github.com/AnatoliiPrylutskyi/nats/commit/3d9148470958d898ffa705cee5894a018c8f7d29

Also I remove global errors in places where it cause errors. All tests are green.

### CODE REVIEW

**Comment by derekcollison** [comment]
Some minor comments, then LGTM.

**Comment by derekcollison** [comment]
Fixup minor comments and we should be good. Thanks.

**Comment by AnatoliiPrylutskyi** [comment]
I add comments to tests, please inform me if you don't like it.

Thanks

**Comment by AnatoliiPrylutskyi** [comment]
Build failed because of timeout, it looks like Travis stuck on golang download.

**Comment by derekcollison** [comment]
I will take a look. Can you replace the time.Sleep with a Flush?

**Comment by AnatoliiPrylutskyi** [comment]
I already replaces it

**Comment by derekcollison** [comment]
ok thanks.

**Pull request merged**
