### PR TITLE
Add option for allowing custom Dialers

### PR DESCRIPTION
**Pull request by wallyqs**
The Golang [Dialer](https://golang.org/pkg/net/#Dialer) has a number of options which would be convenient to allow users customizing them.
This changeset adds a `nats.Dialer` func for setting custom dialers (e.g. to activate opt-in `DualStack` support) which would be used when attempting to establish a connection to the server, still using by default the [DialTimeout](https://golang.org/pkg/net/#DialTimeout) behavior as it is currently.

### CODE REVIEW

**Comment by derekcollison** [comment]
Check why travis tests failed?

**Comment by kozlovic** [comment]
@wallyqs Could you rebase?

**Comment by wallyqs** [comment]
@kozlovic thanks for following up, rebased and tests are passing now :)

**Comment by kozlovic** [comment]
LGTM

**Pull request merged**
