### PR TITLE
Optimize for larger messages.

### PR DESCRIPTION
**Pull request by kozlovic**
This was already present in the server.

### CODE REVIEW

**Comment by kozlovic** [comment]
Ok, I guess you mean writing a new test that can access internals, right?

**Comment by derekcollison** [comment]
If we need to. I would check current coverage, just want to make sure all new code is covered with tests.

**Comment by kozlovic** [comment]
It's not. I will work on a test that check those.

**Comment by derekcollison** [comment]
Thanks.

**Comment by derekcollison** [comment]
Can you rebase and resolve conflicts?

**Comment by kozlovic** [comment]
Will do. I knew this was going to happen with the other PR ;-)

**Pull request merged**
